# Generated by Django 5.0.6 on 2024-07-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipo_de_Carrera',
        ),
        migrations.DeleteModel(
            name='Titulo',
        ),
        migrations.AddField(
            model_name='carrera',
            name='duracion',
            field=models.IntegerField(default=4, verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='titulos',
            field=models.ManyToManyField(to='app1.materia'),
        ),
    ]
